# Settings that the LAMMPS build will import when this package library is used
# The default settings assume that HDF5 support is integrated into the standard
# distribution and search paths and thus only needs to link the HDF5 library.

h5md_SYSINC = -I /usr/include/hdf5/serial 
h5md_SYSLIB = -L /usr/lib/x86_64-linux-gnu/hdf5/serial/ -lhdf5
h5md_SYSPATH =
