#! /usr/bin/env python
# -*- coding: utf-8 -*-

import molsys
#import molsys.mol as mol
#import molsys.util.atomtyper as atomtyper
import sys


name = sys.argv[1]

m = molsys.mol()
m.read(name)
at = molsys.util.atomtyper(m)
at()
#m.write(name)

frag = molsys.util.fragmentizer()
#frag(m, plot=name.split(".")[0])
frag(m)
m.write(name)

