#!/usr/bin/env python
# -*- coding: utf-8 -*-

########################################################################
#
#  Skript to sample the reference Information
#  to an hdf5 file. It needs an loaded Turbomole 
#  Environment because it uses t2x to read the optimized
#  structure. In addition you have to have the hessian stored 
#  in your control file. It is recommended to start aoforce with the 
#  $noproj keyword in order to get an unprojected hessian. The 
#  reference calculation files has to be in a directory called
#  ref/<tag>.
#
#########################################################################


from weaver import FF_api
import molsys.stow as stow

option = [
        ['', 'n', 'name'],
        [None, 'p', 'path'],
        ['', 'c', 'comment']]
          

shellval = stow.main(stow.sys.argv[1:], option)
name = shellval[0]
if shellval[1] is None: 
    path = name+'.hdf5'
else:
    path = shellval[1]
comment = shellval[2]

api = FF_api()
api.set_FFref(name, path, comment)

