#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed May 24 14:15:57 2017

@author: johannes
"""

import click
from mofplus import admin_api, user_api, FF_api


@click.group()
@click.pass_context
def admin(ctx):
    ctx.obj["api"] = admin_api()
    pass


@admin.command()
@click.pass_context
@click.option('--ff', default = "MOF-FF")
def list_FFrefs(ctx,ff):
    click.echo(ctx.obj["api"].list_FFrefs(str(ff)))
    
@admin.command()
@click.pass_context
@click.argument('n')
@click.argument('h5', type = click.Path(exists=True))
@click.argument('mf', type = click.Path(exists=True))
def set_FFref(ctx,n,h5,mf):
    ctx.obj["api"].set_FFref(str(n),str(h5),str(mf))


if __name__ == "__main__":
    admin(obj={})
    



#@click.group()
#@click.option('--debug/--no-debug', default=False)
#@click.pass_context
#def cli(ctx, debug):
#    ctx.obj['DEBUG'] = debug

#@cli.command()
#@click.pass_context
#def sync(ctx):
#    click.echo('Debug is %s' % (ctx.obj['DEBUG'] and 'on' or 'off'))

#if __name__ == '__main__':
#    cli(obj={})