#!/usr/bin/env python
# -*- coding: utf-8 -*-

########################################################################
#
#  Scipt to convert from txyz to xyz
#
#########################################################################


import assign_FF
import molsys.stow as stow
import ff_gen.tools as tools
import ff_gen.refclass as refclass
import numpy
import string
import copy


if __name__ == "__main__":

    option = [
            ['', 'i', 'txyzfile'],
            ['', 'o', 'keyfile'],
            [True, 'v', 'print vars'],
            ['', 'r', 'reference file'],
            [True, 's', 'strbnd']]

    shellval = stow.main(stow.sys.argv[1:], option)

    fxyz = shellval[0]
    fkey = shellval[1]
    var  = shellval[2]
    fref = shellval[3]

    prefix = fxyz.split('.')[0]
    if fkey == '': fkey = prefix + '.key'
    if fref == '': fref = prefix
    frefsplit = fref.split('.')
    if fref != 'hdf5' and frefsplit[-1] == 'hdf5': fref = ".".join(frefsplit[:-1])
    strbnd = shellval[4]

    key = tools.keycreator(fxyz,fref)
    key.get_angles()
    key.get_atoms()
    key.get_charges()
    key.get_vdws()
    key.get_bonds()
    key.get_dihedrals()
    key.write_empty_key(fkey,var,strbnd)

