#!/bin/bash

###   EXPERIMENTAL SCRIPT: USE AT YOUR OWN RISK ################################ 

NAME="$1" # do not use underscores
GEO=$NAME".xyz"
KEY=$NAME".key"

NITER=$2 # only one significant figure
EITER=$(python -c "print ('%.e' % $NITER).replace('+0','')")
FOLD=$NAME"_"$EITER
if [ -d "$NAME" ]
then
    echo '"'$NAME'"' directory already exists
    exit 1
fi

if [ -d "$FOLD" ]
then
    echo '"'$FOLD'"' directory already exists
    exit 1
fi

REFFILE="outcmaesfit.dat"
REFPATH="$NAME/$REFFILE"

ls -d $NAME"_"* 2> /dev/null | egrep -qv _?e? && { echo "Existing conflicting directories"; exit 1; }
fit-cma -c $NAME.xyz -i $NITER > fit-$EITER & PID=$!
while :;
do
    sleep .5
    if [[ -e "$REFPATH" ]]
    then
        whipbar "$REFPATH" $((NITER+1))
        plook $PID
        notify-send -i emblem-important $FOLD "Fitting accomplished"
        break
    fi
done
cp $NAME.key $NAME
mv $NAME $FOLD
mv fit-$EITER $FOLD
rm -f molsys.log
