#!/usr/bin/env python
# -*- coding: utf-8 -*-

########################################################################
#
#  Skript to sample the reference Information
#  to an hdf5 file. It needs an loaded Turbomole 
#  Environment because it uses t2x to read the optimized
#  structure. In addition you have to have the hessian stored 
#  in your control file. It is recommended to start aoforce with the 
#  $noproj keyword in order to get an unprojected hessian. The 
#  reference calculation files has to be in a directory called
#  ref/<tag>.
#
#########################################################################


import pydlpoly
import molsys.stow as stow

option = [
        ['', 'c', 'txyzfile'],
        ['', 'k', 'keyfile']]

shellval = stow.main(stow.sys.argv[1:], option)
fxyz  = shellval[0]
fkey  = shellval[1]
prefix = fxyz.split('.')[0]
if fkey == '': fkey = prefix + '.key'

pd = pydlpoly.pydlpoly('test')
pd.setup(xyz=fxyz, key=fkey)

pd.MIN_lbfgs(0.01)
pd.write_tinker_xyz('opt.txyz')

