#!/usr/bin/env python
# -*- coding: utf-8 -*-

########################################################################
#
#  Scipt to convert from txyz to xyz
#
#########################################################################


import ff_gen.IOmod as IOmod
import molsys.stow as stow

option = [
        ['', 'i', 'txyzfile'],
        ['', 'o', 'xyzfile']]

shellval = stow.main(stow.sys.argv[1:], option)

if shellval[0] == shellval[1]:
    print 'ERROR: Infut file equal to outpu file!!!'
    exit()

IO = IOmod.io()
elements,atypes,xyz,cnct,cell,boundarycond = IO.read_tinker_xyz(shellval[0])
IO.write_xyz(shellval[1],elements, xyz)

