#!/usr/bin/env python
# -*- coding: utf-8 -*-

########################################################################
#
#  Script to convert from xyz to txyz
#
#########################################################################


import ff_gen.IOmod as IOmod
import molsys.stow as stow
import string
import unit_cell

option = [
        ['', 'i', 'xyzfile'],
        ['', 'o', 'txyzfile'],
        ['0.1', 't', 'tresh'],
        ['', 'c', 'cell']]

shellval = stow.main(stow.sys.argv[1:], option)

fxyz = shellval[0]
ftxyz = shellval[1]
tresh = string.atof(shellval[2])
cell = shellval[3]

IO = IOmod.io()
IO.read_xyz(fxyz)
if cell:
  # cell parameter must have the following format: "a b c alpha beta gamma"
  # a b c in Angstrom, alpha beta gamma in deg
  cell_list = [float(i) for i in cell.split()]
  cell = unit_cell.vectors_from_abc(cell_list)
  IO.set_cell(cell)
  IO.remove_duplicates()
else:
  IO.set_cell(None)
IO.generate_cnct(tresh = tresh)
IO.set_atomtypes()
IO.write_tinker_xyz(ftxyz)

