ECHO_TEST: successfully loaded cmcc frontend worker!

LAUNCHPAD_LOC: /home/johannes/.fireworks/my_launchpad.yaml
FWORKER_LOC: /home/johannes/.fireworks/my_fworker.yaml
QUEUEADAPTER_LOC: /home/johannes/.fireworks/my_qadapter.yaml
