#! /usr/bin/env python
# -*- coding: utf-8 -*-

import molsys.mol as mol
import molsys.util.atomtyper as atomtyper
import sys


name = sys.argv[1]

m = mol()
m.read(name)
at = atomtyper(m)
at()

for i, e in enumerate(m.elems):
    if e == 'h':
        if len(m.conn[i]) == 1:
            if m.atypes[m.conn[i][0]] == 'c3_h1n2':
                m.atypes[i] = 'h1_c1S'


m.write(name)
