#!/usr/bin/env python
# -*- coding: utf-8 -*-

########################################################################
#
#  Script to convert different structure file formats based on molsys
#
#########################################################################


import sys
import string
import unit_cell
import molsys.mol as mol


fi = sys.argv[1]
fo = sys.argv[2]
fi_type = fi.split('.')[-1]
fo_type = fo.split('.')[-1]


m = mol()
m.read(fi, ftype = fi_type)
if fi_type == 'xyz':
    m.detect_conn(remove_duplicates = True)
    m.set_nofrags()

m.write(fo, ftype = fo_type)
